language: python

matrix:
  include:
    - python: 2.6
      env: TOXENV="py26"
    - python: 2.7
      env: TOXENV="copying,py27"

before_install:
  - pip install tox

install:
  - pip install .

script:
- tox
