[tox]
envlist = copying,{py310,py313,py314}-{lint,tests,cli}
skip_missing_interpreters = True

[gh-actions]
python =
    3.10: py310
    3.13: py313
    3.14: py314

[testenv]
setenv =
    tests: {[testenv:tests]setenv}
passenv =
    tests: {[testenv:tests]passenv}
deps =
    tests: {[testenv:tests]deps}
    lint: {[testenv:lint]deps}
    cli: {[testenv:cli]deps}
commands =
    tests: {[testenv:tests]commands}
    lint: {[testenv:lint]commands}
    cli: {[testenv:cli]commands}
allowlist_externals =
    copying: {[testenv:copying]allowlist_externals}
    cli: {[testenv:cli]allowlist_externals}

[testenv:tests]
setenv = MPLCONFIGDIR = {toxinidir}/tests_utils/matplotlib
passenv = MPLCONFIGDIR
deps =
    git+https://github.com/iot-lab/cli-tools.git@master#egg=iotlabcli
    -rtests_utils/test-requirements.txt
commands =
    pytest {posargs}

[testenv:cli]
deps =
    git+https://github.com/iot-lab/cli-tools.git@master#egg=iotlabcli
allowlist_externals =
    /bin/bash
    /usr/bin/bash
commands =
    bash -exc "for i in plot_oml_consum plot_oml_radio plot_oml_traj iotlab-plot; do $i --help >/dev/null; done"

[testenv:copying]
allowlist_externals =
    /bin/bash
    /usr/bin/bash
commands =
    bash tests_utils/check_license.sh

[testenv:lint]
deps =
    -rtests_utils/test-requirements.txt
commands =
    pylint oml_plot_tools
    ruff check oml_plot_tools
    ruff format --check oml_plot_tools
    isort --check-only oml_plot_tools
